export const companies = [
  {
    name: "Apple",
    image: "/public/assets/apple.png",
  },
  {
    name: "Dell",
    image: "/public/assets/dell.png",
  },
  {
    name: "HP",
    image: "/public/assets/hp.png",
  },
  {
    name: "Lenovo",
    image: "/public/assets/lenovo.png",
  },
  {
    name: "Acer",
    image: "/public/assets/acer.png",
  },
  {
    name: "Asus",
    image: "/public/assets/asus.png",
  },
  {
    name: "MSI",
    image: "/public/assets/msi.png",
  },
  {
    name: "Razer",
    image: "/public/assets/razer.png",
  },
  {
    name: "Microsoft",
    image: "/public/assets/microsoft.png",
  },
  {
    name: "Samsung",
    image: "/public/assets/samsung.png",
  },
  {
    name: "Toshiba",
    image: "/public/assets/toshiba.png",
  },
  {
    name: "LG",
    image: "/public/assets/lg.png",
  },
  {
    name: "Huawei",
    image: "/public/assets/huawei.png",
  },
  {
    name: "Google",
    image: "/public/assets/google.png",
  },
  {
    name: "Sony",
    image: "/public/assets/sony.png",
  },
  {
    name: "Panasonic",
    image: "/public/assets/panasonic.png",
  },
  {
    name: "Xiaomi",
    image: "/public/assets/xiaomi.png",
  },
  {
    name: "Alienware",
    image: "/public/assets/alienware.png",
  },
  {
    name: "Vaio",
    image: "/public/assets/vaio.png",
  },
  {
    name: "Gateway",
    image: "/public/assets/gateway.png",
  },
  {
    name: "Fujitsu",
    image: "/public/assets/fujitsu.png",
  },
  {
    name: "CyberPowerPC",
    image: "/public/assets/cyberpowerpc.png",
  },
  {
    name: "Origin PC",
    image: "/public/assets/originpc.png",
  },
  {
    name: "System76",
    image: "/public/assets/system76.png",
  },
  {
    name: "iBUYPOWER",
    image: "/public/assets/ibuypower.png",
  },
  {
    name: "Clevo",
    image: "/public/assets/clevo.png",
  },
  {
    name: "Shuttle",
    image: "/public/assets/shuttle.png",
  },
  {
    name: "ZOTAC",
    image: "/public/assets/zotac.png",
  },
  {
    name: "ECS (Elitegroup Computer Systems)",
    image: "/public/assets/ecs.png",
  },
];

export const models = [
  "Apple MacBook Air M2",
  "Apple MacBook Pro M2",
  "Dell XPS 13",
  "Dell Inspiron 15",
  "Dell Alienware m15 R7",
  "HP Spectre x360 14",
  "HP Envy 15",
  "HP Omen 17",
  "Lenovo ThinkPad X1 Carbon",
  "Lenovo Yoga 9i",
  "Lenovo Legion 5 Pro",
  "Acer Swift 3",
  "Acer Predator Helios 300",
  "Asus ZenBook 14",
  "Asus ROG Strix Scar 15",
  "Asus TUF Gaming A15",
  "MSI GF65 Thin",
  "MSI GE76 Raider",
  "Razer Blade 15",
  "Razer Book 13",
  "Microsoft Surface Laptop 4",
  "Microsoft Surface Pro 8",
  "Samsung Galaxy Book Pro",
  "Samsung Odyssey Neo G9",
  "Toshiba Tecra A50",
  "LG Gram 17",
  "LG UltraGear 27GP950",
  "Huawei MateBook X Pro",
  "Huawei MateBook 14",
  "Google Pixelbook Go",
  "Sony VAIO SX14",
  "Panasonic Toughbook 55",
  "Xiaomi Mi Notebook Pro",
  "Xiaomi RedmiBook Pro",
  "Alienware x17 R2",
  "Alienware Aurora R13",
  "Vaio Z Flip",
  "Gateway Creator Series",
  "Fujitsu Lifebook U937",
  "CyberPowerPC Gamer Xtreme",
  "Origin PC EVO15-S",
  "System76 Lemur Pro",
  "iBUYPOWER Slate 4",
  "Clevo NH70",
  "Hasee K670E",
  "Shuttle XPC SH370R8",
  "ZOTAC MAG NANO",
  "ECS LIVA Z3 Plus",
  "Apple MacBook Pro 16",
  "Dell Latitude 7420",
  "HP Elite Dragonfly",
  "Lenovo ThinkPad P52",
  "Acer ConceptD 7",
  "Asus Chromebook Flip C436",
  "MSI Creator 15",
  "Razer Blade Stealth 13",
  "Microsoft Surface Book 3",
  "Samsung Notebook 9 Pro",
  "Toshiba Satellite Pro C50",
  "LG UltraWide 34WK95U",
  "Huawei MateBook D15",
  "Google Pixelbook",
  "Sony VAIO SX12",
  "Panasonic Toughbook 33",
  "Xiaomi Mi Gaming Laptop",
  "Alienware Area-51m",
  "Vaio SX14",
  "Gateway Laptop 15.6",
  "Fujitsu Stylistic Q738",
  "CyberPowerPC Tracer III",
  "Origin PC GENESIS",
  "System76 Oryx Pro",
  "iBUYPOWER Element CL",
  "Clevo P750TM1",
  "Hasee X2",
  "Shuttle DS77U",
  "ZOTAC ZBOX CI329 Nano",
  "ECS LIVA Q1",
  "Dell G15 Gaming",
  "HP Pavilion 14",
  "Lenovo IdeaPad 5",
  "Acer Nitro 5",
  "Asus ROG Flow Z13",
  "MSI Summit E14",
  "Razer Blade 17",
  "Microsoft Surface Studio 2",
  "Samsung Book Flex",
  "Toshiba Portege X30",
  "LG UltraGear 34GP83A",
  "Huawei MateBook 13",
  "Google Pixelbook Pixel",
  "Sony VAIO A12",
  "Panasonic Toughpad FZ-G1",
  "Xiaomi Mi Notebook Air",
  "Alienware m17 R6",
  "Vaio S11",
  "Gateway NV55S05u",
  "Fujitsu Esprimo D558",
  "CyberPowerPC Gamer Master",
  "Origin PC Millennium",
  "System76 Galago Pro",
  "iBUYPOWER Trace 4",
  "Clevo P775TM1-G",
  "Hasee K580D",
  "Shuttle XPC XH510G",
  "ZOTAC MAG HD-NG",
  "ECS LIVA X2",
];

export const operatingSystems = [
  "Windows 10 Home",
  "Windows 10 Pro",
  "Windows 10 Enterprise",
  "Windows 11 Home",
  "Windows 11 Pro",
  "Windows 11 Enterprise",
  "macOS Monterey",
  "macOS Big Sur",
  "macOS Catalina",
  "Ubuntu",
  "Fedora",
  "Debian",
  "Linux Mint",
  "Red Hat Enterprise Linux",
  "CentOS",
  "openSUSE",
  "Arch Linux",
  "Manjaro",
  "Kali Linux",
  "Chrome OS",
  "Google Fuchsia",
  "Android",
  "iOS",
  "Elementary OS",
  "Zorin OS",
  "Pop!_OS",
  "Solus",
  "EndeavourOS",
  "ReactOS",
  "Haiku OS",
  "Qubes OS",
  "Deepin",
  "Slackware",
  "Tails",
  "Puppy Linux",
  "Clear Linux",
  "Tiny Core Linux",
  "Parrot OS",
  "Knoppix",
  "SUSE Linux Enterprise",
  "OpenBSD",
  "FreeBSD",
  "NetBSD",
  "AIX",
  "HP-UX",
  "Solaris",
  "UnixWare",
  "Raspbian",
  "Puppy Linux",
  "Joli OS",
  "Mageia",
  "Void Linux",
  "NixOS",
  "SliTaz",
  "Mopria OS",
  "Netrunner",
  "Ubuntu Studio",
  "Tails OS",
  "ReactOS",
  "OpenIndiana",
  "Razor-qt",
  "BlackArch",
];

export const processorCompanies = [
  "Intel",
  "AMD",
  "Apple",
  "Qualcomm",
  "NVIDIA",
  "IBM",
  "ARM",
  "Via Technologies",
  "MediaTek",
  "Samsung",
  "Huawei",
  "Cavium",
  "Marvell",
  "RISC-V",
  "Texas Instruments",
  "Cirrus Logic",
  "Zhaoxin",
  "Fujitsu",
  "Siemens",
  "Broadcom",
  "Freescale (now NXP)",
  "NXP Semiconductors",
  "Transmeta",
  "Spansion",
  "Sun Microsystems",
  "MIPS Computer Systems",
  "Sierra Semiconductor",
  "Motorola",
  "Analog Devices",
  "National Semiconductor",
  "Toshiba",
  "Intersil",
  "Xilinx",
  "Altera",
  "Broadcom",
  "Softex",
  "Parallels",
  "SAMD",
  "Lattice Semiconductor",
  "S3 Graphics",
  "PowerVR",
  "Zilog",
  "STMicroelectronics",
  "NexGen",
  "EmuTech",
];

export const processorModels = [
  "Intel Core i3-12100",
  "Intel Core i5-12600K",
  "Intel Core i7-13700",
  "Intel Core i9-13900K",
  "AMD Ryzen 3 4100",
  "AMD Ryzen 5 5600X",
  "AMD Ryzen 7 5800X",
  "AMD Ryzen 9 5900X",
  "Apple M1",
  "Apple M1 Pro",
  "Apple M1 Max",
  "Apple M2",
  "Qualcomm Snapdragon 8cx Gen 3",
  "Qualcomm Snapdragon 8 Gen 2",
  "NVIDIA ARM Cortex-A78",
  "IBM POWER9",
  "ARM Cortex-A72",
  "ARM Cortex-A55",
  "Via C7-M",
  "MediaTek Dimensity 1200",
  "Samsung Exynos 2100",
  "Huawei Kirin 9000",
  "Cavium ThunderX2",
  "Marvell Armada 8040",
  "RISC-V SiFive U84",
  "Texas Instruments OMAP 5",
  "Cirrus Logic CS4208",
  "Zhaoxin KX-5000",
  "Fujitsu A64FX",
  "Siemens ARM Cortex-A76",
  "Broadcom BCM2711",
  "Freescale i.MX 8",
  "NXP Semiconductors i.MX 6",
  "Transmeta Crusoe",
  "Spansion S29GL",
  "Sun Microsystems UltraSPARC T1",
  "MIPS R10000",
  "Sierra Semiconductor 3320",
  "Motorola 68000",
  "Analog Devices Blackfin",
  "National Semiconductor Geode",
  "Toshiba TZ1000",
  "Intersil ISL1208",
  "Xilinx Zynq-7000",
  "Altera Cyclone V",
  "Broadcom BCM2837",
  "Softex PICO",
  "SAMD21",
  "Lattice Semiconductor iCE40",
  "S3 Graphics Savage 4",
  "PowerVR SGX543",
  "Zilog Z80",
  "STMicroelectronics STM32",
  "NexGen Nx586",
  "EmuTech Emu386",
];

export const graphicsCards = [
  "NVIDIA GeForce RTX 4090",
  "NVIDIA GeForce RTX 4080",
  "NVIDIA GeForce RTX 4070",
  "NVIDIA GeForce RTX 4060",
  "NVIDIA GeForce GTX 1660 Ti",
  "NVIDIA GeForce GTX 1650",
  "AMD Radeon RX 7900 XTX",
  "AMD Radeon RX 7800 XT",
  "AMD Radeon RX 7700 XT",
  "AMD Radeon RX 7600 XT",
  "AMD Radeon RX 6500 XT",
  "AMD Radeon RX 6400",
  "Intel Arc A770",
  "Intel Arc A750",
  "Intel Arc A580",
  "Intel Iris Xe Max",
  "NVIDIA Quadro RTX 8000",
  "NVIDIA Quadro RTX 6000",
  "NVIDIA Quadro P5000",
  "NVIDIA Tesla V100",
  "NVIDIA Tesla T4",
  "AMD Radeon Pro VII",
  "AMD Radeon Pro WX 8200",
  "AMD Radeon Pro WX 7100",
  "ASUS ROG Strix GTX 1080 Ti",
  "MSI Gaming X Trio 3080",
  "Gigabyte AORUS Xtreme 3090",
  "EVGA FTW3 Ultra Gaming 3070",
  "ZOTAC Gaming GeForce RTX 3060 Ti",
  "Palit GamingPro RTX 2060 Super",
  "XFX Speedster MERC 319 RX 6800 XT",
  "Sapphire Nitro+ RX 6900 XT",
  "ASRock Phantom Gaming X RX 5700 XT",
  "PowerColor Red Devil RX 6600 XT",
  "NVIDIA GeForce GTX 1080 Ti",
  "NVIDIA GeForce GTX 1070",
  "NVIDIA GeForce GTX 1060",
  "AMD Radeon R9 390X",
  "AMD Radeon R9 380",
  "Intel Iris Plus Graphics G7",
  "Intel HD Graphics 630",
  "Intel UHD Graphics 750",
  "NVIDIA GeForce MX250",
  "NVIDIA GeForce MX330",
  "AMD Radeon R5 M330",
  "AMD Radeon R7 M445",
  "NVIDIA Quadro K5200",
  "NVIDIA Quadro K4200",
  "NVIDIA GeForce GTX 980 Ti",
  "NVIDIA GeForce GTX 970",
  "AMD Radeon R9 295X2",
  "AMD Radeon R9 290X",
  "Intel HD Graphics 4000",
  "Intel Iris Graphics 5100",
  "Intel Iris Xe Graphics G7",
];

export const ramModels = [
  "Corsair Vengeance LPX 8GB DDR4-3200",
  "G.SKILL Ripjaws V 16GB DDR4-3600",
  "Crucial Ballistix 32GB DDR4-3200",
  "Kingston HyperX Fury 16GB DDR4-2666",
  "ADATA XPG Gammix D30 8GB DDR4-3200",
  "Patriot Viper 4 16GB DDR4-3000",
  "HyperX Impact 16GB DDR4-2400 (SODIMM)",
  "Samsung 16GB DDR4-3200",
  "Team T-Force Vulcan Z 32GB DDR4-3200",
  "Hynix 8GB DDR4-2666",
  "Crucial Ballistix MAX 64GB DDR4-4000",
  "G.SKILL Trident Z RGB 32GB DDR4-3600",
  "Corsair Dominator Platinum 16GB DDR4-3200",
  "Kingston HyperX Predator 32GB DDR4-3200",
  "OLOy Warhawk 16GB DDR4-3200",
  "G.SKILL Sniper X 16GB DDR4-3000",
  "Patriot Viper Steel 16GB DDR4-3600",
  "Crucial Ballistix Sport LT 8GB DDR4-2666",
  "Kingston ValueRAM 8GB DDR4-2133",
  "Corsair Vengeance LPX 32GB DDR4-3200",
  "ADATA XPG Spectrix D41 16GB DDR4-3200",
  "G.SKILL Aegis 8GB DDR4-2400",
  "Team T-Force Dark Z 16GB DDR4-3200",
  "Crucial DDR4-2400 8GB",
  "Corsair Vengeance LPX 16GB DDR4-2400",
  "G.SKILL Ripjaws 4 32GB DDR4-2133",
  "Patriot Viper Elite 8GB DDR4-2666",
  "HyperX Fury 8GB DDR4-2133",
  "Adata Premier DDR4 16GB 2666MHz",
  "Kingston HyperX Impact 32GB DDR4-3200",
  "Crucial Ballistix Tactical 16GB DDR4-2666",
  "G.SKILL Trident Z Royal 32GB DDR4-3600",
  "Corsair Vengeance LPX 64GB DDR4-3200",
  "Kingston HyperX Fury 8GB DDR4-3200",
  "Patriot Viper 8GB DDR4-2400",
  "Team T-Force Xtreem ARGB 32GB DDR4-3600",
  "ADATA XPG Z1 8GB DDR4-3000",
  "Crucial Ballistix Elite 16GB DDR4-3200",
  "Corsair Dominator Platinum RGB 32GB DDR4-3600",
  "G.SKILL Trident Z Neo 16GB DDR4-3600",
  "Kingston ValueRAM 4GB DDR4-2400",
  "Patriot Viper 4 Blackout 16GB DDR4-3000",
  "G.SKILL Ripjaws V 8GB DDR4-3200",
  "Crucial Ballistix Sport 8GB DDR4-3000",
  "Corsair Vengeance LPX 8GB DDR4-2400",
  "Team T-Force Vulcan 8GB DDR4-3000",
];

export const displayOptions = [
  "Full HD (1920x1080)",
  "Quad HD (2560x1440)",
  "4K UHD (3840x2160)",
  "5K (5120x2880)",
  "6K (6016x3384)",
  "8K UHD (7680x4320)",
  "HD (1280x720)",
  "Retina Display",
  "IPS (In-Plane Switching)",
  "TN (Twisted Nematic)",
  "VA (Vertical Alignment)",
  "OLED (Organic Light Emitting Diode)",
  "Mini-LED",
  "QLED (Quantum Dot LED)",
  "Touchscreen",
  "Non-Touchscreen",
  "Anti-Glare",
  "Glossy",
  "HDR10",
  "HDR400",
  "HDR600",
  "G-SYNC",
  "FreeSync",
  "120Hz Refresh Rate",
  "144Hz Refresh Rate",
  "240Hz Refresh Rate",
  "360Hz Refresh Rate",
  "2K (2048x1080)",
  "Ultrawide (2560x1080)",
  "Super Ultrawide (3440x1440)",
  "Curved",
  "Flat",
  "Aspect Ratio 16:9",
  "Aspect Ratio 16:10",
  "Aspect Ratio 21:9",
  "Aspect Ratio 32:9",
  "4:3 Aspect Ratio",
  "11.6-inch Display",
  "13.3-inch Display",
  "14-inch Display",
  "15.6-inch Display",
  "17.3-inch Display",
  "Ultra HD (3840x2160)",
  "FHD+ (2220x1080)",
  "WQHD (3440x1440)",
  "WUXGA (1920x1200)",
  "WVGA (800x480)",
  "XGA (1024x768)",
  "SXGA (1280x1024)",
  "UXGA (1600x1200)",
  "2.5K (2560x1440)",
  "4K OLED",
  "5K Retina",
  "1440p",
  "3D Display",
  "Blue Light Filter",
];

export const storageOptions = [
  "128GB SSD",
  "256GB SSD",
  "512GB SSD",
  "1TB SSD",
  "2TB SSD",
  "4TB SSD",
  "8TB SSD",
  "16TB SSD",
  "32GB eMMC",
  "64GB eMMC",
  "128GB eMMC",
  "256GB eMMC",
  "500GB HDD",
  "1TB HDD",
  "2TB HDD",
  "4TB HDD",
  "8TB HDD",
  "12TB HDD",
  "16TB HDD",
  "RAID 0 (Striping)",
  "RAID 1 (Mirroring)",
  "RAID 5 (Striped Disks with Parity)",
  "RAID 10 (Striped Mirrors)",
  "M.2 NVMe SSD",
  "M.2 SATA SSD",
  "PCIe NVMe SSD",
  "SATA III SSD",
  "SATA II SSD",
  "External SSD (Portable)",
  "External HDD (Portable)",
  "Hybrid Drive (SSHD)",
  "NAS (Network Attached Storage)",
  "SAN (Storage Area Network)",
  "Cloud Storage (e.g., Google Drive, Dropbox)",
];
